// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Suggests daily specials based on available ingredients and current inventory to minimize waste and maximize profits.
 *
 * - suggestDailySpecial - A function that suggests daily specials.
 * - SuggestDailySpecialInput - The input type for the suggestDailySpecial function.
 * - SuggestDailySpecialOutput - The return type for the suggestDailySpecial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestDailySpecialInputSchema = z.object({
  availableIngredients: z
    .array(z.string())
    .describe('List of available ingredients in the kitchen.'),
  currentInventory: z
    .record(z.number())
    .describe('Current inventory levels for each ingredient (e.g., {tomato: 5, basil: 2}).'),
});
export type SuggestDailySpecialInput = z.infer<typeof SuggestDailySpecialInputSchema>;

const SuggestDailySpecialOutputSchema = z.object({
  suggestedSpecials: z
    .array(z.string())
    .describe('A list of suggested daily specials based on available ingredients.'),
  reasoning: z
    .string()
    .describe('Explanation of why these specials are suggested, considering waste minimization and profit maximization.'),
});
export type SuggestDailySpecialOutput = z.infer<typeof SuggestDailySpecialOutputSchema>;

export async function suggestDailySpecial(input: SuggestDailySpecialInput): Promise<SuggestDailySpecialOutput> {
  return suggestDailySpecialFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestDailySpecialPrompt',
  input: {schema: SuggestDailySpecialInputSchema},
  output: {schema: SuggestDailySpecialOutputSchema},
  prompt: `You are a restaurant manager, and you will be suggesting daily specials based on available ingredients and current inventory.

Available Ingredients: {{availableIngredients}}
Current Inventory: {{currentInventory}}

Suggest a list of daily specials using the available ingredients and current inventory. Explain your reasoning considering waste minimization and profit maximization.
Ensure that the suggested specials are profitable and practical to prepare with the current stock.

Output in the following JSON format:
{
  "suggestedSpecials": ["Special 1", "Special 2"],
  "reasoning": "Explanation of why these specials are suggested."
}
`,
});

const suggestDailySpecialFlow = ai.defineFlow(
  {
    name: 'suggestDailySpecialFlow',
    inputSchema: SuggestDailySpecialInputSchema,
    outputSchema: SuggestDailySpecialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
