
import type { MenuItem } from '@/types';

export const initialMenuItems: MenuItem[] = [
  // Appetizers (5)
  {
    id: 'APP001',
    name: 'Crispy Spring Rolls',
    category: 'Appetizers',
    price: 8.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'spring rolls',
    availability: true,
    description: 'Golden fried spring rolls filled with vegetables and glass noodles.',
    isVegetarian: true,
  },
  {
    id: 'APP002',
    name: 'Garlic Bread with Cheese',
    category: 'Appetizers',
    price: 7.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'garlic bread cheese',
    availability: true,
    description: 'Toasted bread with garlic butter and melted mozzarella.',
    isVegetarian: true,
  },
  {
    id: 'APP003',
    name: 'Chicken Wings (6 pcs)',
    category: 'Appetizers',
    price: 10.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'chicken wings',
    availability: true,
    description: 'Spicy and tangy chicken wings served with a blue cheese dip.',
    isVegetarian: false,
  },
  {
    id: 'APP004',
    name: 'Bruschetta Classic',
    category: 'Appetizers',
    price: 9.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'bruschetta',
    availability: true,
    description: 'Grilled bread rubbed with garlic and topped with tomato, basil, and olive oil.',
    isVegetarian: true,
  },
  {
    id: 'APP005',
    name: 'Stuffed Mushrooms',
    category: 'Appetizers',
    price: 9.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'stuffed mushrooms',
    availability: false,
    description: 'Mushrooms stuffed with herbs, cheese, and breadcrumbs.',
    isVegetarian: true,
  },

  // Soups (4)
  {
    id: 'SOUP001',
    name: 'Tomato Basil Soup',
    category: 'Soups',
    price: 6.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'tomato soup',
    availability: true,
    description: 'Creamy tomato soup with fresh basil.',
    isVegetarian: true,
  },
  {
    id: 'SOUP002',
    name: 'Chicken Noodle Soup',
    category: 'Soups',
    price: 7.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'chicken soup',
    availability: true,
    description: 'Classic chicken noodle soup with tender chicken and vegetables.',
    isVegetarian: false,
  },
  {
    id: 'SOUP003',
    name: 'Minestrone Soup',
    category: 'Soups',
    price: 6.75,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'minestrone soup',
    availability: true,
    description: 'Hearty Italian vegetable soup with pasta.',
    isVegetarian: true,
  },
   {
    id: 'SOUP004',
    name: 'Cream of Mushroom',
    category: 'Soups',
    price: 6.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'mushroom soup',
    availability: true,
    description: 'Rich and creamy mushroom soup.',
    isVegetarian: true,
  },

  // Salads (4)
  {
    id: 'SAL001',
    name: 'Caesar Salad',
    category: 'Salads',
    price: 10.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'caesar salad',
    availability: true,
    description: 'Romaine lettuce, croutons, parmesan cheese, and Caesar dressing.',
    isVegetarian: true,
    discount: 10,
  },
  {
    id: 'SAL002',
    name: 'Greek Salad',
    category: 'Salads',
    price: 11.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'greek salad',
    availability: true,
    description: 'Tomatoes, cucumbers, olives, feta cheese, and a light vinaigrette.',
    isVegetarian: true,
  },
  {
    id: 'SAL003',
    name: 'Grilled Chicken Salad',
    category: 'Salads',
    price: 13.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'chicken salad',
    availability: true,
    description: 'Mixed greens topped with grilled chicken breast, and your choice of dressing.',
    isVegetarian: false,
  },
  {
    id: 'SAL004',
    name: 'Quinoa Salad',
    category: 'Salads',
    price: 12.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'quinoa salad',
    availability: true,
    description: 'Healthy quinoa salad with mixed vegetables and a lemon-herb dressing.',
    isVegetarian: true,
  },

  // Main Courses (10)
  {
    id: 'MAIN001',
    name: 'Grilled Salmon',
    category: 'Main Course',
    price: 18.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'grilled salmon',
    availability: true,
    description: 'Fresh salmon fillet grilled to perfection, served with roasted vegetables.',
    isVegetarian: false,
  },
  {
    id: 'MAIN002',
    name: 'Chicken Alfredo Pasta',
    category: 'Pasta', // Also a main course
    price: 15.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'chicken alfredo',
    availability: true,
    description: 'Creamy Alfredo pasta with grilled chicken strips.',
    isVegetarian: false,
  },
  {
    id: 'MAIN003',
    name: 'Beef Steak',
    category: 'Main Course',
    price: 22.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'beef steak',
    availability: true,
    description: 'Tender beef steak cooked to your liking, served with mashed potatoes.',
    isVegetarian: false,
  },
  {
    id: 'MAIN004',
    name: 'Vegetable Stir-Fry',
    category: 'Main Course',
    price: 13.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'vegetable stirfry',
    availability: true,
    description: 'Assorted fresh vegetables stir-fried in a savory sauce, served with rice.',
    isVegetarian: true,
  },
  {
    id: 'MAIN005',
    name: 'Lamb Chops',
    category: 'Main Course',
    price: 20.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'lamb chops',
    availability: true,
    description: 'Grilled lamb chops marinated in herbs, served with mint sauce.',
    isVegetarian: false,
  },
   {
    id: 'MAIN006',
    name: 'Margherita Pizza',
    category: 'Main Course',
    price: 14.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'margherita pizza',
    availability: true,
    description: 'Classic pizza with tomato, mozzarella, and basil.',
    isVegetarian: true,
  },
  {
    id: 'MAIN007',
    name: 'Pepperoni Pizza',
    category: 'Main Course',
    price: 16.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'pepperoni pizza',
    availability: true,
    description: 'Pizza topped with spicy pepperoni and mozzarella.',
    isVegetarian: false,
  },
  {
    id: 'MAIN008',
    name: 'Fish and Chips',
    category: 'Main Course',
    price: 15.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'fish chips',
    availability: true,
    description: 'Battered fish fillets served with french fries and tartar sauce.',
    isVegetarian: false,
  },
  {
    id: 'MAIN009',
    name: 'Vegetarian Lasagna',
    category: 'Pasta',
    price: 14.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'vegetarian lasagna',
    availability: true,
    description: 'Layers of pasta, ricotta cheese, and mixed vegetables in a tomato sauce.',
    isVegetarian: true,
  },
  {
    id: 'MAIN010',
    name: 'Shepherds Pie',
    category: 'Main Course',
    price: 16.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'shepherds pie',
    availability: true,
    description: 'Ground lamb and vegetables topped with mashed potato.',
    isVegetarian: false,
  },

  // Pasta (additional 4, total 6 with the ones in Main Course)
  {
    id: 'PASTA001',
    name: 'Spaghetti Bolognese',
    category: 'Pasta',
    price: 14.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'spaghetti bolognese',
    availability: true,
    description: 'Classic spaghetti with a rich meat and tomato sauce.',
    isVegetarian: false,
  },
  {
    id: 'PASTA002',
    name: 'Penne Arrabbiata',
    category: 'Pasta',
    price: 12.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'penne arrabbiata',
    availability: true,
    description: 'Penne pasta in a spicy tomato sauce with garlic and chili.',
    isVegetarian: true,
  },
   {
    id: 'PASTA003',
    name: 'Carbonara',
    category: 'Pasta',
    price: 15.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'pasta carbonara',
    availability: true,
    description: 'Spaghetti with pancetta, egg, pecorino cheese, and black pepper.',
    isVegetarian: false,
  },
   {
    id: 'PASTA004',
    name: 'Seafood Linguine',
    category: 'Pasta',
    price: 17.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'seafood linguine',
    availability: true,
    description: 'Linguine pasta with mixed seafood in a light tomato sauce.',
    isVegetarian: false,
  },


  // Burgers (5)
  {
    id: 'BURG001',
    name: 'Classic Beef Burger',
    category: 'Burgers',
    price: 12.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'beef burger',
    availability: true,
    description: 'Juicy beef patty with lettuce, tomato, onion, and pickles.',
    isVegetarian: false,
  },
  {
    id: 'BURG002',
    name: 'Cheese Burger',
    category: 'Burgers',
    price: 13.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'cheese burger',
    availability: true,
    description: 'Classic beef burger with a slice of cheddar cheese.',
    isVegetarian: false,
    discount: 20,
  },
  {
    id: 'BURG003',
    name: 'Chicken Burger',
    category: 'Burgers',
    price: 11.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'chicken burger',
    availability: true,
    description: 'Grilled or fried chicken breast burger with mayo and lettuce.',
    isVegetarian: false,
  },
  {
    id: 'BURG004',
    name: 'Veggie Burger',
    category: 'Burgers',
    price: 10.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'veggie burger',
    availability: true,
    description: 'A delicious plant-based patty with all the classic toppings.',
    isVegetarian: true,
  },
   {
    id: 'BURG005',
    name: 'Spicy Jalapeno Burger',
    category: 'Burgers',
    price: 14.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'spicy burger',
    availability: true,
    description: 'Beef burger with jalapenos, spicy mayo, and pepper jack cheese.',
    isVegetarian: false,
  },

  // Sandwiches (5)
  {
    id: 'SAND001',
    name: 'Club Sandwich',
    category: 'Sandwiches',
    price: 11.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'club sandwich',
    availability: true,
    description: 'Triple-decker sandwich with chicken, bacon, lettuce, tomato, and mayo.',
    isVegetarian: false,
  },
  {
    id: 'SAND002',
    name: 'BLT Sandwich',
    category: 'Sandwiches',
    price: 9.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'blt sandwich',
    availability: true,
    description: 'Classic bacon, lettuce, and tomato sandwich.',
    isVegetarian: false,
  },
  {
    id: 'SAND003',
    name: 'Grilled Cheese Sandwich',
    category: 'Sandwiches',
    price: 8.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'grilled cheese',
    availability: true,
    description: 'Buttery grilled bread with melted cheddar cheese.',
    isVegetarian: true,
  },
  {
    id: 'SAND004',
    name: 'Tuna Melt Sandwich',
    category: 'Sandwiches',
    price: 10.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'tuna melt',
    availability: true,
    description: 'Tuna salad with melted cheese on toasted bread.',
    isVegetarian: false,
  },
  {
    id: 'SAND005',
    name: 'Caprese Sandwich',
    category: 'Sandwiches',
    price: 9.75,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'caprese sandwich',
    availability: true,
    description: 'Fresh mozzarella, tomatoes, basil, and balsamic glaze on ciabatta.',
    isVegetarian: true,
  },

  // Desserts (6)
  {
    id: 'DES001',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 8.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'lava cake',
    availability: true,
    description: 'Warm chocolate cake with a gooey molten center, served with ice cream.',
    isVegetarian: true,
  },
  {
    id: 'DES002',
    name: 'New York Cheesecake',
    category: 'Desserts',
    price: 7.99,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'cheesecake',
    availability: true,
    description: 'Classic creamy cheesecake with a graham cracker crust.',
    isVegetarian: true,
  },
  {
    id: 'DES003',
    name: 'Tiramisu',
    category: 'Desserts',
    price: 8.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'tiramisu',
    availability: true,
    description: 'Italian dessert made with ladyfingers, mascarpone cheese, and coffee.',
    isVegetarian: true,
  },
  {
    id: 'DES004',
    name: 'Apple Pie',
    category: 'Desserts',
    price: 7.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'apple pie',
    availability: true,
    description: 'Warm apple pie with a flaky crust, served with vanilla ice cream.',
    isVegetarian: true,
  },
  {
    id: 'DES005',
    name: 'Ice Cream (2 scoops)',
    category: 'Desserts',
    price: 5.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'ice cream scoops',
    availability: true,
    description: 'Choice of vanilla, chocolate, or strawberry ice cream.',
    isVegetarian: true,
  },
   {
    id: 'DES006',
    name: 'Brownie with Ice Cream',
    category: 'Desserts',
    price: 8.25,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'brownie icecream',
    availability: true,
    description: 'Warm chocolate brownie topped with vanilla ice cream and chocolate sauce.',
    isVegetarian: true,
  },

  // Beverages (7)
  {
    id: 'BEV001',
    name: 'Coca-Cola',
    category: 'Beverages',
    price: 2.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'coca cola can',
    availability: true,
    description: 'Classic Coca-Cola.',
    isVegetarian: true,
  },
  {
    id: 'BEV002',
    name: 'Fresh Orange Juice',
    category: 'Beverages',
    price: 4.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'orange juice',
    availability: true,
    description: 'Freshly squeezed orange juice.',
    isVegetarian: true,
  },
  {
    id: 'BEV003',
    name: 'Espresso',
    category: 'Beverages',
    price: 3.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'espresso shot',
    availability: true,
    description: 'Strong black coffee.',
    isVegetarian: true,
  },
  {
    id: 'BEV004',
    name: 'Cappuccino',
    category: 'Beverages',
    price: 4.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'cappuccino',
    availability: true,
    description: 'Espresso with steamed milk and foam.',
    isVegetarian: true,
  },
  {
    id: 'BEV005',
    name: 'Mineral Water',
    category: 'Beverages',
    price: 2.00,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'water bottle',
    availability: true,
    description: 'Still or sparkling mineral water.',
    isVegetarian: true,
  },
  {
    id: 'BEV006',
    name: 'Iced Tea',
    category: 'Beverages',
    price: 3.50,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'iced tea',
    availability: true,
    description: 'Refreshing lemon or peach iced tea.',
    isVegetarian: true,
  },
  {
    id: 'BEV007',
    name: 'Mango Lassi',
    category: 'Beverages',
    price: 4.75,
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'mango lassi',
    availability: true,
    description: 'Creamy yogurt-based mango smoothie.',
    isVegetarian: true,
  },
];

export const categories = [
  { name: 'All', icon: 'LayoutGrid' },
  { name: 'Appetizers', icon: 'Salad' }, // Using Salad for Appetizers
  { name: 'Soups', icon: 'Soup' },
  { name: 'Salads', icon: 'LeafyGreen' },
  { name: 'Pasta', icon: 'Grape' }, // Using Grape as a placeholder for Pasta
  { name: 'Main Course', icon: 'Fish' }, // Or UtensilsCrossed
  { name: 'Burgers', icon: 'Sandwich' },
  { name: 'Sandwiches', icon: 'Sandwich' },
  { name: 'Desserts', icon: 'Cake' },
  { name: 'Beverages', icon: 'Coffee' },
];
